service: escape-orbit-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-east-1  # Change to your preferred region
  environment:
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/EscapeOrbitLeaderboard"

functions:
  app:
    handler: lambda-dynamodb.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    LeaderboardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EscapeOrbitLeaderboard
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline 